#!/bin/bash

cd /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution

)


out20cee3a0="${tmpDir}/out.$$" err20cee3a0="${tmpDir}/err.$$"
mkfifo "$out20cee3a0" "$err20cee3a0"
trap 'rm "$out20cee3a0" "$err20cee3a0"' EXIT
touch '/cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/stdout' '/cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/stderr'
tee '/cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/stdout' < "$out20cee3a0" &
tee '/cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/stderr' < "$err20cee3a0" >&2 &
(
cd /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution


# create empty qc messages file
touch qc_messages.txt

# write WDL arrays to files
printf "%s\n" sample0 sample0 > sample_ids_list.txt
printf "%s\n" /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/inputs/1771176815/fakeCram0.cram /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/inputs/1771176815/fakeCram1.cram > crams_list.txt
printf "%s\n" /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/inputs/1771176815/fakeCram0.cram.crai /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/inputs/1771176815/fakeCram1.cram.crai > cram_indices_list.txt

# validate that the number of CRAMs, CRAIs, and sample IDs match
if [ 2 -ne 2 ] || [ 2 -ne 2 ]; then
    echo "Mismatch in the number of CRAMs (2), CRAIs (2), and sample IDs (2)." >> qc_messages.txt
else
    echo "Number of CRAMs, CRAIs, and sample IDs match: 2."
fi

# validate that sample IDs are unique
unique_sample_ids=$(cat sample_ids_list.txt | sort -u | wc -l)
if [ $unique_sample_ids -ne 2 ]; then
    # find duplicate sample IDs
    duplicate_sample_ids=$(cat sample_ids_list.txt | sort | uniq -d | tr '\n' ', ' | sed 's/, $//')
    echo "Duplicate sample IDs found: ${duplicate_sample_ids}" >> qc_messages.txt
else
    echo "Sample IDs are unique."
fi

# ensure all crams end with .cram and all cram indices end with .crai
crams_with_wrong_extension=$(cat crams_list.txt | grep -vE "\.cram$" || true)
if [ ! -z "${crams_with_wrong_extension}" ]; then
    echo "The following CRAM files do not have a .cram extension: ${crams_with_wrong_extension}" >> qc_messages.txt
else
    echo "All CRAM files have the correct .cram extension."
fi
cram_indices_with_wrong_extension=$(cat cram_indices_list.txt | grep -vE "\.crai$" || true)
if [ ! -z "${cram_indices_with_wrong_extension}" ]; then
    echo "The following CRAM index files do not have a .crai extension: ${cram_indices_with_wrong_extension}" >> qc_messages.txt
else
    echo "All CRAM index files have the correct .crai extension."
fi

# passes_qc is true if qc_messages is empty
if [ ! -s qc_messages.txt ]; then
    echo "true" > passes_qc.txt
else
    echo "false" > passes_qc.txt
fi

# This task should always succeed
exit 0
)  > "$out20cee3a0" 2> "$err20cee3a0"
echo $? > /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution
sync


)
mv /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/rc.tmp /cromwell-executions/InputQC/20cee3a0-8d38-416f-99d9-6fb0bd485b77/call-ValidateCramsAndIndices/execution/rc

