#!/usr/bin/env Rscript

library('optparse')

option_list <- list(
	make_option(c('-i','--input'),
		type='character',
		default=NULL,
		dest='input',
		help='directory path of 10x matrix used for input'),
         make_option(c('-v','--version'),
		type='character',
		default='V2',
		dest='version',
		help='version of 10X matrix, allowed values V2 and V3'),
	make_option(c('-o','--output'),
		type='character',
		default=NULL,
		dest='output',
		help='output rds file name')
)
	
## Parse arguements
opt_parser <- OptionParser(option_list=option_list);
opt <- parse_args(opt_parser);

#' Prints a message to stderr and exits R with error code 1
#' @param msg message to standard error
errorExit <- function(msg) {
    cat(msg,file=stderr());
    quit(save='no',status=1);
}

## Check arguments
if(is.null(opt$input)) errorExit("Input 10X matrix is not specified\n");
if(!opt$version %in% c('V2','V3')) 
     errorExit(paste0("Not allowed value for version parameter: ", opt$version, 
     			   ". Version must be one of 'V2' or 'V3."))
if(is.null(opt$output)) errorExit("Output rds file not specified");


## read10xMatrix from the nbHelpers package

#' @title  Read 10x matrix
#' @description This function reads a matrix generated by the 10x processing pipeline
#' from the specified directory and returns it. It aborts if one of the required
#' files in the specified directory do not exist.
#' @param path location of 10x output
#' @param version version of 10x output to read, must be one of 'V2' or 'V3'
#' @return read matrix
#' @import Matrix
#' @import methods
#' @export read10xMatrix
read10xMatrix <- function(path, version='V2') {
    if(version == 'V2') {
        unpackFunction <- I
        suffix <- ''
    } else if (version == 'V3') {
        unpackFunction <- gzfile
        suffix <- '.gz'
    } else {
        stop('Unknown file version!')
    }
    matrixFile <- paste0(path, '/matrix.mtx', suffix);
    if (version == 'V2') {
        genesFile <- paste0(path, '/genes.tsv', suffix);
    } else if (version == 'V3') {
        genesFile <- paste0(path, '/features.tsv', suffix);
    }
    barcodesFile <- paste0(path, '/barcodes.tsv', suffix);
    if (!file.exists(matrixFile)) { stop('Matrix file does not exist');  }
    if (!file.exists(genesFile)) { stop('Genes file does not exist'); }
    if (!file.exists(barcodesFile)) { stop('Barcodes file does not exist'); }
    x <- as(Matrix::readMM(unpackFunction(matrixFile)), 'dgCMatrix')
    genes <- read.table(unpackFunction(genesFile));
    rownames(x) <- genes[,2];
    barcodes <- read.table(unpackFunction(barcodesFile));
    colnames(x) <- barcodes[,1]
    invisible(x);
}

## Main Script


## Read the 10x matrix and save as an RDS file
d <- read10xMatrix(opt$input, version=opt$version)
saveRDS(d, opt$output)
