version: 1.2
workflows:
  - name: VUMCFastqQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqQC.wdl

  - name: VUMCCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC.wdl

  - name: VUMCMoveFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFile.wdl

  - name: VUMCMoveFastqToCramResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFastqToCramResult.wdl
    
  - name: VUMCGunzippedMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCGunzippedMd5.wdl
    
  - name: VUMCMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMd5.wdl
    
  - name: VUMCCopyFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyFile.wdl
 
  - name: VUMCCramReads
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramReads.wdl

  - name: VUMCCramQCCombined
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQCCombined.wdl

  - name: VUMCSamHeader
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCSamHeader.wdl

  - name: VUMCDeleteFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteFiles.wdl

  - name: VUMCBamToCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCBamToCram.wdl

  - name: VUMCMoveCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveCram.wdl

  - name: VUMCDeleteBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteBam.wdl

  - name: VUMCExomeGermlineSingleSampleFromFastq
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wes/VUMCExomeGermlineSingleSampleFromFastq.wdl

  - name: VUMCExomeReprocessAlignedCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wes/VUMCExomeReprocessAlignedCram.wdl

  - name: VUMCMoveSingleSampleWGSResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCMoveSingleSampleWGSResult.wdl

  - name: VUMCUnmappedBamToAlignedCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCram.wdl

  - name: VUMCUnmappedBamToAlignedCramMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCramMoveResult.wdl

  - name: VUMCPlink2FilterSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2FilterSample.wdl

  - name: VUMCPlink2
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2.wdl
  
  - name: VUMCMoveSingleSampleWESResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wes/VUMCMoveSingleSampleWESResult.wdl

  - name: VUMCFixCramReference
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFixCramReference.wdl

  - name: VUMCUnmappedBamToAlignedCramNoBamQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCramNoBamQC.wdl

  - name: VUMCUnmappedBamToAlignedCramNoBamQCMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCramNoBamQCMoveResult.wdl

  - name: VUMCFastqToAlignedCramNoBamQCFast
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCFastqToAlignedCramNoBamQCFast.wdl

  - name: VUMCReprocessAlignedCramNoBamQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCReprocessAlignedCramNoBamQC.wdl

  - name: VUMCFileSize
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFileSize.wdl

  - name: VUMCVcfExcludeSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfExcludeSamples.wdl

  - name: VUMCVcfIncludeSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfIncludeSamples.wdl

  - name: CombineGvsChromosome
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/joint_genotyping/CombineGvsChromosome.wdl

  - name: VUMCHaplotypecallerReblock
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCHaplotypecallerReblock.wdl

  - name: VUMCHaplotypecallerReblockMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCHaplotypecallerReblockMoveResult.wdl

  - name: VUMCMappedCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCMappedCramQC.wdl

  - name: VUMCPlinkIncludeSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCPlinkIncludeSamples.wdl

  - name: VUMCContamination
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCContamination.wdl

  - name: VUMCVariantCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCVariantCalling.wdl

  - name: VUMCVariantCallingMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCVariantCallingMoveResult.wdl

  - name: VUMCCollectWgsMetrics
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCCollectWgsMetrics.wdl

  - name: VUMCIlluminaCoverage
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCIlluminaCoverage.wdl

  - name: VUMCVcfInfo
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfInfo.wdl

  - name: VUMCPlink2BedToPgen
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCPlink2BedToPgen.wdl

  - name: VUMCPlink2BedToBgen
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCPlink2BedToBgen.wdl

  - name: VUMCBed2HailMatrix
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCBed2HailMatrix.wdl

  - name: VUMCPlink2FilterRegion
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2FilterRegion.wdl

  - name: VUMCVcfRenameSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfRenameSamples.wdl

  - name: VUMCBed2GDS
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCBed2GDS.wdl

  - name: VUMCPlink2Filter
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2Filter.wdl

  - name: VUMCVcf2HailMatrix
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcf2HailMatrix.wdl

  - name: VUMCHailMatrixExtractSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrixExtractSamples.wdl

  - name: VUMCHailMatrix2Vcf
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrix2Vcf.wdl

  - name: VUMCVcfExtractSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfExtractSamples.wdl

  - name: VUMCVcf2GDS
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcf2GDS.wdl

  - name: VUMCBedInfo
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCBedInfo.wdl

  - name: VUMCVcfExtractRegions
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfExtractRegions.wdl

  - name: VUMCVcfMoveFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfMoveFiles.wdl

  - name: VUMCVcfNumVariants
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfNumVariants.wdl

  - name: VUMCHailMatrixInfo
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrixInfo.wdl

  - name: VUMC_vcftools828Filters
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMC_vcftools828Filters.wdl
  
  - name: VUMC_overlappingVariantList
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMC_overlapingVariantList.wdl

  - name: VUMCPrepareGenotypeData
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCPrepareGenotypeData.wdl 

  - name: VUMCGenotypePCA
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCGenotypePCA.wdl 

  - name: VUMCRegenie
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/GWAS/VUMCRegenie.wdl

  - name: VUMCVcfIndex
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfIndex.wdl

  - name: VUMCExtractRegionAGD
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCExtractRegionAGD.wdl

  - name: VUMCPlink2Bgen
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2Bgen.wdl

  - name: VUMCHailMatrixExtractRegions
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrixExtractRegions.wdl

  - name: VUMCAnnovar
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCAnnovar.wdl

  - name: VUMCGetGeneLocus
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/annotation/VUMCGetGeneLocus.wdl

  - name: VUMCPrepareGeneGenotype
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCPrepareGeneGenotype.wdl

  - name: VUMCPreparePhenotype
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCPreparePhenotype.wdl

  - name: VUMCLinearAssociation
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCLinearAssociation.wdl

  - name: VUMCPrepareGeneGenotypeWorkflow
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCPrepareGeneGenotypeWorkflow.wdl

  - name: VUMCPhewas
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCPhewas.wdl

  - name: VUMCGenePhewas
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/agd/VUMCGenePhewas.wdl

  - name: VUMCMergePgenFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCMergePgenFiles.wdl

  - name: VUMCQCFilterAndMergePgen
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/GWAS/VUMCQCFilterAndMergePgen.wdl
