version: 1.2
workflows:

  - name: ArrayImputationQuotaConsumed
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation_beagle/ArrayImputationQuotaConsumed.wdl

  - name: atac
    subclass: WDL
    primaryDescriptorPath:
      /pipelines/skylab/atac/atac.wdl

  - name: BuildIndices
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/build_indices/BuildIndices.wdl

  - name: CramToUnmappedBams
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/cram_to_unmapped_bams/CramToUnmappedBams.wdl

  - name: determine_hq_sites_intersection
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/determine_hq_sites_intersection.wdl
  
  - name: ExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/exome/ExomeGermlineSingleSample.wdl

  - name: ExomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/exome/ExomeReprocessing.wdl

  - name: IlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/genotyping/illumina/IlluminaGenotypingArray.wdl

  - name: Imputation
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation/Imputation.wdl

  - name: ImputationBeagle
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation_beagle/ImputationBeagle.wdl

  - name: JointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/JointGenotyping.wdl

  - name: Multiome
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/multiome/Multiome.wdl

  - name: Optimus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/optimus/Optimus.wdl
    testParameterFiles:
          -  /warp/pipelines/skylab/optimus/example_inputs/human_v3_example.json

  - name: PairedTag
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/paired_tag/PairedTag.wdl

  - name: PeakCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/peak_calling/PeakCalling.wdl

  - name: ReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/reblocking/ReblockGVCF.wdl

  - name: RNAWithUMIsPipeline
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/rna_seq/RNAWithUMIsPipeline.wdl

  - name: run_ancestry
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/run_ancestry.wdl
 
  - name: Smartseq2_Single_Nucleus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus/SmartSeq2SingleNucleus.wdl

  - name: Smartseq2_Single_Nucleus_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus_multisample/MultiSampleSmartSeq2SingleNucleus.wdl

  - name: SlideSeq
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/slideseq/SlideSeq.wdl

  - name: SlideTags
    subclass: WDL
    primaryDescriptorPath: /beta-pipelines/skylab/slidetags/SlideTags.wdl

  - name: snm3C-seq
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/snm3C/snm3C.wdl

  - name: TestATAC
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestATAC.wdl

  - name: TestCramToUnmappedBams
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestCramToUnmappedBams.wdl

  - name: TestExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestExomeGermlineSingleSample.wdl

  - name: TestExomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestExomeReprocessing.wdl

  - name: TestIlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestIlluminaGenotypingArray.wdl

  - name: TestImputation
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestImputation.wdl

  - name: TestImputationBeagle
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestImputationBeagle.wdl

  - name: TestJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestJointGenotyping.wdl

  - name: TestMultiome
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestMultiome.wdl

  - name: TestMultiSampleSmartSeq2SingleNucleus
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestMultiSampleSmartSeq2SingleNucleus.wdl

  - name: TestOptimus
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestOptimus.wdl

  - name: TestPairedTag
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestPairedTag.wdl

  - name: TestPeakCalling
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestPeakCalling.wdl

  - name: TestReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestReblockGVCF.wdl

  - name: TestRNAWithUMIsPipeline
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestRNAWithUMIsPipeline.wdl

  - name: TestSlideSeq
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestSlideSeq.wdl

  - name: Testsnm3C
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/Testsnm3C.wdl

  - name: TestUltimaGenomicsJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestUltimaGenomicsJointGenotyping.wdl

  - name: TestUltimaGenomicsWholeGenomeCramOnly
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestUltimaGenomicsWholeGenomeCramOnly.wdl

  - name: TestUltimaGenomicsWholeGenomeGermline
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestUltimaGenomicsWholeGenomeGermline.wdl

  - name: TestVariantCalling
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestVariantCalling.wdl

  - name: TestWholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestWholeGenomeGermlineSingleSample.wdl

  - name: TestWholeGenomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestWholeGenomeReprocessing.wdl

  - name: UltimaGenomicsWholeGenomeGermline
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/ugwgs/UltimaGenomicsWholeGenomeGermline.wdl

  - name: UltimaGenomicsJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/UltimaGenomics/UltimaGenomicsJointGenotyping.wdl

  - name: UltimaGenomicsWholeGenomeCramOnly
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/somatic/single_sample/ugwgs/UltimaGenomicsWholeGenomeCramOnly.wdl

  - name: VariantCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/variant_calling/VariantCalling.wdl

  - name: vds_to_vcf.wdl
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/vds_to_vcf.wdl
  
  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

  - name: WholeGenomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeReprocessing.wdl