version: 1.3
workflows:
  - name: VUMCFastqToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/VUMCFastqToAlignedBam.wdl

  - name: VUMCUnmappedBamToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/VUMCUnmappedBamToAlignedBam.wdl    