version: 1.2
workflows:
  - name: JointGenotypingByChromosomePartOne
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/by_chromosome/JointGenotypingByChromosomePartOne.wdl

  - name: JointGenotypingByChromosomePartTwo
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/by_chromosome/JointGenotypingByChromosomePartTwo.wdl

  - name: VUMCFastqToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedBam.wdl

  - name: VUMCUnmappedBamToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCUnmappedBamToAlignedBam.wdl

  - name: VUMCFastqQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqQC.wdl

  - name: VUMCCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC.wdl

  - name: VUMCCopyBamFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyBamFile.wdl

  - name: VUMCMoveFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFile.wdl

  - name: VUMCMoveFastqToBamResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFastqToBamResult.wdl

  - name: VUMCMoveHaplotypecallerResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCMoveHaplotypecallerResult.wdl
    
  - name: VUMCGunzippedMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCGunzippedMd5.wdl
    
  - name: VUMCMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMd5.wdl
    
  - name: VUMCCopyFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyFile.wdl
 
  - name: VUMCCramQC2
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC2.wdl

  - name: VUMCCramQCCombined
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC_combined.wdl

  - name: VUMCSamHeader
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCSamHeader.wdl

  - name: VUMCDeleteFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteFiles.wdl

  - name: VUMCBamToCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCBamToCram.wdl

  - name: VUMCFastqToAlignedCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedCram.wdl

  - name: VUMCMoveCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveCram.wdl

  - name: VUMCDeleteBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteBam.wdl

  - name: VUMCHaplotypeCaller
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/haplotypecaller-gvcf-gatk4.wdl

  - name: VUMCJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/joint_genotyping/JointGenotyping.wdl
