version: 1.2
workflows:

  - name: Optimus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/optimus/Optimus.wdl
    testParameterFiles:
          -  /warp/pipelines/skylab/optimus/example_inputs/human_v3_example.json

  - name: snm3C-seq
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/snm3C/snm3C.wdl

  - name: Smartseq2_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_multisample/MultiSampleSmartSeq2.wdl

  - name: Smartseq2_Single_Sample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_sample/SmartSeq2SingleSample.wdl

  - name: Smartseq2_Single_Nucleus_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus_multisample/MultiSampleSmartSeq2SingleNucleus.wdl

  - name: Smartseq2_Single_Nucleus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus/SmartSeq2SingleNucleus.wdl

  - name: IlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/genotyping/illumina/IlluminaGenotypingArray.wdl

  - name: scATAC
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/scATAC/scATAC.wdl

  - name: JointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/JointGenotyping.wdl

  - name: ExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/exome/ExomeGermlineSingleSample.wdl

  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

  - name: OptimusHcaAdapter
    subclass: WDL
    primaryDescriptorPath: /projects/optimus/CreateOptimusAdapterMetadata.wdl
    
  - name: Ss2HcaAdapter
    subclass: WDL
    primaryDescriptorPath: /projects/smartseq2/CreateSs2AdapterMetadata.wdl

  - name: CEMBA
    subclass: WDL
    primaryDescriptorPath: /pipelines/cemba/cemba_methylcseq/CEMBA.wdl

  - name: ReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/reblocking/ReblockGVCF.wdl

  - name: Arrays
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/single_sample/Arrays.wdl

  - name: Imputation
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation/Imputation.wdl

  - name: RNAWithUMIsPipeline
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/rna_seq/RNAWithUMIsPipeline.wdl

  - name: BroadInternalRNAWithUMIs
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/rna_seq/BroadInternalRNAWithUMIs.wdl

  - name: Arrays_TDR
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/arrays/single_sample/BroadInternalArrays.wdl

  - name: Imputation_TDR
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/arrays/imputation/BroadInternalImputation.wdl

  - name: UltimaGenomicsWholeGenomeGermline
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/ugwgs/UltimaGenomicsWholeGenomeGermline.wdl

  - name: BroadInternalUltimaGenomics
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/dna_seq/germline/single_sample/UltimaGenomics/BroadInternalUltimaGenomics.wdl

  - name: UltimaGenomicsJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/UltimaGenomics/UltimaGenomicsJointGenotyping.wdl

  - name: UltimaGenomicsWholeGenomeCramOnly
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/somatic/single_sample/ugwgs/UltimaGenomicsWholeGenomeCramOnly.wdl

  - name: BuildIndices
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/build_indices/BuildIndices.wdl

  - name: SlideSeq
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/slideseq/SlideSeq.wdl
    
  - name: Multiome
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/multiome/Multiome.wdl
  
  - name: PairedTag
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/paired_tag/PairedTag.wdl
    
  - name: atac
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/atac/atac.wdl

  - name: TestIlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestIlluminaGenotypingArray.wdl

  - name: TestPairedTag
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestPairedTag.wdl
    
  - name: TestOptimus
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestOptimus.wdl

  - name: TestMultiome
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestMultiome.wdl

  - name: TestReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestReblockGVCF.wdl

  - name: Testsnm3C
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/Testsnm3C.wdl
    
  - name: VariantCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/variant_calling/VariantCalling.wdl

  - name: SlideTags
    subclass: WDL
    primaryDescriptorPath: /beta-pipelines/skylab/slidetags/SlideTags.wdl
