version: 1.2
workflows:
  # - name: VUMCFastqToAlignedBam
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedBam.wdl

  # - name: VUMCUnmappedBamToAlignedBam
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCUnmappedBamToAlignedBam.wdl

  - name: VUMCFastqQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqQC.wdl

  - name: VUMCCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC.wdl

  # - name: VUMCCopyBamFile
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyBamFile.wdl

  - name: VUMCMoveFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFile.wdl

  # - name: VUMCMoveFastqToBamResult
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFastqToBamResult.wdl

  - name: VUMCMoveFastqToCramResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFastqToCramResult.wdl

  - name: VUMCMoveHaplotypecallerResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCMoveHaplotypecallerResult.wdl
    
  - name: VUMCGunzippedMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCGunzippedMd5.wdl
    
  - name: VUMCMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMd5.wdl
    
  - name: VUMCCopyFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyFile.wdl
 
  - name: VUMCCramReads
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramReads.wdl

  - name: VUMCCramQCCombined
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQCCombined.wdl

  - name: VUMCSamHeader
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCSamHeader.wdl

  - name: VUMCDeleteFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteFiles.wdl

  - name: VUMCBamToCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCBamToCram.wdl

  # - name: VUMCFastqToAlignedCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedCram.wdl

  - name: VUMCMoveCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveCram.wdl

  - name: VUMCDeleteBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteBam.wdl

  # - name: VUMCJointGenotyping
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/joint_genotyping/JointGenotyping.wdl

  # - name: VUMCRealignCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCRealignCram.wdl

  # - name: WholeGenomeGermlineSingleSampleFromCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSampleFromCram.wdl

  # - name: VUMCWholeGenomeGermlineSingleSampleFromFastq
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCWholeGenomeGermlineSingleSampleFromFastq.wdl

  # - name: VUMCWholeGenomeGermlineSingleSampleFromMappedCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCWholeGenomeGermlineSingleSampleFromMappedCram.wdl

  - name: VUMCExomeGermlineSingleSampleFromFastq
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wes/VUMCExomeGermlineSingleSampleFromFastq.wdl

  - name: VUMCExomeReprocessAlignedCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wes/VUMCExomeReprocessAlignedCram.wdl

  - name: VUMCMoveSingleSampleWGSResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCMoveSingleSampleWGSResult.wdl

  - name: VUMCUnmappedBamToAlignedCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCram.wdl

  - name: VUMCUnmappedBamToAlignedCramMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCramMoveResult.wdl

  - name: VUMCPlink2FilterSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2FilterSample.wdl

  - name: VUMCPlink2
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2.wdl

  # it always fails in fastq to unmapped bam. I decided to generate unmapped bam as independent step.
  # - name: VUMCMergeFastqWithCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMergeFastqWithCram.wdl

  # - name: VUMCMergeUnmappedBamWithCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMergeUnmappedBamWithCram.wdl
    
  - name: VUMCMoveSingleSampleWESResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wes/VUMCMoveSingleSampleWESResult.wdl

  - name: VUMCFixCramReference
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFixCramReference.wdl

  - name: VUMCUnmappedBamToAlignedCramNoBamQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCramNoBamQC.wdl

  - name: VUMCUnmappedBamToAlignedCramNoBamQCMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCUnmappedBamToAlignedCramNoBamQCMoveResult.wdl

  # - name: VUMCFastqToAlignedCramNoBamQC
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCFastqToAlignedCramNoBamQC.wdl

  - name: VUMCFastqToAlignedCramNoBamQCFast
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCFastqToAlignedCramNoBamQCFast.wdl

  # - name: VUMCFastqToUnmappedCram
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToUnmappedCram.wdl

  - name: VUMCReprocessAlignedCramNoBamQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCReprocessAlignedCramNoBamQC.wdl

  - name: VUMCFileSize
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFileSize.wdl

  - name: VUMCVcfExcludeSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfExcludeSamples.wdl

  - name: VUMCVcfIncludeSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfIncludeSamples.wdl

  - name: CombineGvsChromosome
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/joint_genotyping/CombineGvsChromosome.wdl

  # - name: VUMCHaplotypecallerReblock
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCHaplotypecallerReblock.wdl

  # - name: VUMCHaplotypecallerReblockMoveResult
  #   subclass: WDL
  #   primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCHaplotypecallerReblockMoveResult.wdl

  - name: VUMCMappedCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCMappedCramQC.wdl

  - name: VUMCPlinkIncludeSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCPlinkIncludeSamples.wdl

  - name: VUMCContamination
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCContamination.wdl

  - name: VUMCVariantCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCVariantCalling.wdl

  - name: VUMCVariantCallingMoveResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCVariantCallingMoveResult.wdl

  - name: VUMCCollectWgsMetrics
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCCollectWgsMetrics.wdl

  - name: VUMCIlluminaCoverage
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/single_sample/wgs/VUMCIlluminaCoverage.wdl

  - name: VUMCVcfInfo
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfInfo.wdl

  - name: VUMCPlink2BedToPgen
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCPlink2BedToPgen.wdl

  - name: VUMCPlink2BedToBgen
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCPlink2BedToBgen.wdl

  - name: VUMCBed2HailMatrix
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCBed2HailMatrix.wdl

  - name: VUMCPlink2FilterRegion
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2FilterRegion.wdl

  - name: VUMCVcfRenameSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfRenameSamples.wdl

  - name: VUMCBed2GDS
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCBed2GDS.wdl

  - name: VUMCPlink2Filter
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/plink/VUMCPlink2Filter.wdl

  - name: VUMCVcf2HailMatrix
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcf2HailMatrix.wdl

  - name: VUMCHailMatrixExtractSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrixExtractSamples.wdl

  - name: VUMCHailMatrix2Vcf
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrix2Vcf.wdl

  - name: VUMCVcfExtractSamples
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfExtractSamples.wdl

  - name: VUMCVcf2GDS
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcf2GDS.wdl

  - name: VUMCBedInfo
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCBedInfo.wdl

  - name: VUMCVcfExtractRegions
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfExtractRegions.wdl

  - name: VUMCVcfMoveFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfMoveFiles.wdl

  - name: VUMCVcfNumVariants
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCVcfNumVariants.wdl

  - name: VUMCHailMatrixInfo
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/genotype/VUMCHailMatrixInfo.wdl

  - name: VUMC_vcftools828Filters
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMC_vcftools828Filters.wdl