version: 1.2
workflows:

  - name: aggregate_rsem_results
    subclass: WDL
    primaryDescriptorPath: /all_of_us/rna_seq/aggregate_rsem_results.wdl
  
  - name: ArrayImputationQuotaConsumed
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/arrays/imputation_beagle/ArrayImputationQuotaConsumed.wdl

  - name: ArrayImputationQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/arrays/imputation_beagle/input_qc/ArrayImputationQC.wdl

  - name: atac
    subclass: WDL
    primaryDescriptorPath:
      /pipelines/wdl/atac/atac.wdl

  - name: BuildIndices
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/build_indices/BuildIndices.wdl

  - name: CramToUnmappedBams
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/reprocessing/cram_to_unmapped_bams/CramToUnmappedBams.wdl

  - name: determine_hq_sites_intersection
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/determine_hq_sites_intersection.wdl
  
  - name: ExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/single_sample/exome/ExomeGermlineSingleSample.wdl

  - name: ExomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/reprocessing/exome/ExomeReprocessing.wdl

  - name: FilterandQCVariants
    subclass: WDL
    primaryDescriptorPath: /all_of_us/phasing/filter_and_qc_variants.wdl

  - name: FixItFelixAndVariantCall
    subclass: WDL
    primaryDescriptorPath: /all_of_us/cmrg/FixItFelixAndVariantCall.wdl

  - name: get_wgs_median_coverage
    subclass: WDL
    primaryDescriptorPath: /all_of_us/mitochondria/get_wgs_median_coverage.wdl

  - name: GvsAoUReblockGvcf
    subclass: WDL
    primaryDescriptorPath: /all_of_us/cmrg/GvsAoUReblockGvcf.wdl

  - name: HLAGenotyping
    subclass: WDL
    primaryDescriptorPath: /all_of_us/hla/HLAGenotyping.wdl

  - name: IlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/genotyping/illumina/IlluminaGenotypingArray.wdl

  - name: Imputation
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/arrays/imputation/Imputation.wdl

  - name: ImputationBeagle
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/arrays/imputation_beagle/ImputationBeagle.wdl

  - name: JointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/joint_genotyping/JointGenotyping.wdl

  - name: leafcutter_bam_to_junc
    subclass: WDL
    primaryDescriptorPath: /all_of_us/rna_seq/leafcutter_bam_to_junc.wdl
  
  - name: leafcutter_cluster
    subclass: WDL
    primaryDescriptorPath: /all_of_us/rna_seq/leafcutter_cluster.wdl
    
  - name: MakeTable
    subclass: WDL
    primaryDescriptorPath: /all_of_us/hla/MakeTable.wdl
    
  - name: mitochondria_pipeline
    subclass: WDL
    primaryDescriptorPath: /all_of_us/mitochondria/mitochondria_pipeline.wdl

  - name: mt_coverage_merge
    subclass: WDL
    primaryDescriptorPath: /all_of_us/mitochondria/mt_coverage_merge.wdl

  - name: Multiome
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/multiome/Multiome.wdl

  - name: Optimus
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/optimus/Optimus.wdl
    testParameterFiles:
          -  /warp/pipelines/wdl/optimus/example_inputs/human_v3_example.json

  - name: PairedTag
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/paired_tag/PairedTag.wdl

  - name: pca_only_no_labels
    subclass: WDL
    primaryDescriptorPath: /all_of_us/PCA/pca_only_no_labels.wdl

  - name: PeakCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/peak_calling/PeakCalling.wdl

  - name: ReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/joint_genotyping/reblocking/ReblockGVCF.wdl

  - name: rnaseq_aou
    subclass: WDL
    primaryDescriptorPath: /all_of_us/rna_seq/rnaseq_aou.wdl

  - name: RNAWithUMIsPipeline
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/rna_seq/RNAWithUMIsPipeline.wdl
  
  - name: run_preprocess_admixture_est_rye
    subclass: WDL
    primaryDescriptorPath: /all_of_us/admixture/run_preprocess_admixture_est_rye.wdl
  
  - name: run_admixture_est_rye
    subclass: WDL
    primaryDescriptorPath: /all_of_us/admixture/run_admixture_est_rye.wdl
  
  - name: run_ancestry
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/run_ancestry.wdl
 
  - name: run_relatedness
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/run_relatedness.wdl
  
  - name: run_sample_outlier_qc
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/run_sample_outlier_qc.wdl

  - name: run_sample_outlier_qc_plotting
    subclass: WDL

  - name: Smartseq2_Single_Nucleus
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/smartseq2_single_nucleus/SmartSeq2SingleNucleus.wdl

  - name: Smartseq2_Single_Nucleus_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/smartseq2_single_nucleus_multisample/MultiSampleSmartSeq2SingleNucleus.wdl

  - name: SlideSeq
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/slideseq/SlideSeq.wdl

  - name: SlideTags
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/slidetags/SlideTags.wdl

  - name: snm3C-seq
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/snm3C/snm3C.wdl

  - name: SplitMultisampleVcf
    subclass: WDL

    primaryDescriptorPath: /beta-pipelines/broad/Utilities/SplitMultisampleVCF/SplitMultisampleVCF.wdl
    readMePath: /beta-pipelines/broad/Utilities/SplitMultisampleVCF/README.md

  - name: TestArrayImputationQC
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestArrayImputationQC.wdl

  - name: TestATAC
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestATAC.wdl

  - name: TestCramToUnmappedBams
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestCramToUnmappedBams.wdl

  - name: TestExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestExomeGermlineSingleSample.wdl

  - name: TestExomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestExomeReprocessing.wdl

  - name: TestIlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestIlluminaGenotypingArray.wdl

  - name: TestImputation
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestImputation.wdl

  - name: TestImputationBeagle
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestImputationBeagle.wdl

  - name: TestJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestJointGenotyping.wdl

  - name: TestMultiome
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestMultiome.wdl

  - name: TestMultiSampleSmartSeq2SingleNucleus
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestMultiSampleSmartSeq2SingleNucleus.wdl

  - name: TestOptimus
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestOptimus.wdl

  - name: TestPairedTag
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestPairedTag.wdl

  - name: TestPeakCalling
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestPeakCalling.wdl

  - name: TestReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestReblockGVCF.wdl

  - name: TestRNAWithUMIsPipeline
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestRNAWithUMIsPipeline.wdl

  - name: TestSlideSeq
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestSlideSeq.wdl

  - name: TestSlideTags
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestSlideTags.wdl

  - name: Testsnm3C
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/Testsnm3C.wdl

  - name: TestUltimaGenomicsJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestUltimaGenomicsJointGenotyping.wdl

  - name: TestUltimaGenomicsWholeGenomeCramOnly
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestUltimaGenomicsWholeGenomeCramOnly.wdl

  - name: TestUltimaGenomicsWholeGenomeGermline
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestUltimaGenomicsWholeGenomeGermline.wdl

  - name: TestVariantCalling
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestVariantCalling.wdl

  - name: TestWholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestWholeGenomeGermlineSingleSample.wdl

  - name: TestWholeGenomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /verification/test-wdls/TestWholeGenomeReprocessing.wdl

  - name: UltimaGenomicsWholeGenomeGermline
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/single_sample/ugwgs/UltimaGenomicsWholeGenomeGermline.wdl

  - name: UltimaGenomicsJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/joint_genotyping/UltimaGenomics/UltimaGenomicsJointGenotyping.wdl

  - name: UltimaGenomicsWholeGenomeCramOnly
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/somatic/single_sample/ugwgs/UltimaGenomicsWholeGenomeCramOnly.wdl

  - name: VariantCalling
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/variant_calling/VariantCalling.wdl

  - name: vds_to_vcf
    subclass: WDL
    primaryDescriptorPath: /all_of_us/ancestry/vds_to_vcf.wdl
  
  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

  - name: WholeGenomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /pipelines/wdl/reprocessing/wgs/WholeGenomeReprocessing.wdl
