version: 1.2
workflows:

  - name: Optimus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/optimus/Optimus.wdl
    testParameterFiles:
          -  /warp/pipelines/skylab/optimus/example_inputs/human_v3_example.json

  - name: Smartseq2_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_multisample/MultiSampleSmartSeq2.wdl

  - name: Smartseq2_Single_Sample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_sample/SmartSeq2SingleSample.wdl

  - name: Smartseq2_Single_Nucleus_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus_multisample/MultiSampleSmartSeq2SingleNucleus.wdl

  - name: Smartseq2_Single_Nucleus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus/SmartSeq2SingleNucleus.wdl

  - name: IlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/genotyping/illumina/IlluminaGenotypingArray.wdl

  - name: scATAC
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/scATAC/scATAC.wdl

  - name: JointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/JointGenotyping.wdl

  - name: ExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/exome/ExomeGermlineSingleSample.wdl

  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

  - name: OptimusHcaAdapter
    subclass: WDL
    primaryDescriptorPath: /projects/optimus/CreateOptimusAdapterMetadata.wdl
    
  - name: Ss2HcaAdapter
    subclass: WDL
    primaryDescriptorPath: /projects/smartseq2/CreateSs2AdapterMetadata.wdl

  - name: CEMBA
    subclass: WDL
    primaryDescriptorPath: /pipelines/cemba/cemba_methylcseq/CEMBA.wdl

  - name: ReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/reblocking/ReblockGVCF.wdl

  - name: Arrays
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/single_sample/Arrays.wdl

  - name: Imputation
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation/Imputation.wdl

  - name: RNAWithUMIsPipeline
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/rna_seq/RNAWithUMIsPipeline.wdl

  - name: BroadInternalRNAWithUMIs
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/rna_seq/BroadInternalRNAWithUMIs.wdl

  - name: Arrays_TDR
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/arrays/single_sample/BroadInternalArrays.wdl

  - name: Imputation_TDR
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/arrays/imputation/BroadInternalImputation.wdl

  - name: UltimaGenomicsWholeGenomeGermline
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/ugwgs/UltimaGenomicsWholeGenomeGermline.wdl

  - name: BroadInternalUltimaGenomics
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/internal/dna_seq/germline/single_sample/UltimaGenomics/BroadInternalUltimaGenomics.wdl

  - name: UltimaGenomicsJointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/UltimaGenomics/UltimaGenomicsJointGenotyping.wdl

  - name: UltimaGenomicsWholeGenomeCramOnly
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/somatic/single_sample/ugwgs/UltimaGenomicsWholeGenomeCramOnly.wdl

  - name: BuildIndices
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/build_indices/BuildIndices.wdl

  - name: SlideSeq
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/slideseq/SlideSeq.wdl

  - name: VUMCFastqToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedBam.wdl

  - name: VUMCUnmappedBamToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCUnmappedBamToAlignedBam.wdl

  - name: VUMCFastqQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqQC.wdl

  - name: VUMCCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC.wdl

  - name: VUMCCopyBamFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyBamFile.wdl

  - name: VUMCMoveFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFile.wdl

  - name: VUMCMoveFastqToBamResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveFastqToBamResult.wdl

  - name: VUMCMoveHaplotypecallerResult
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/dna_seq/germline/variant_calling/VUMCMoveHaplotypecallerResult.wdl
    
  - name: VUMCGunzippedMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCGunzippedMd5.wdl
    
  - name: VUMCMd5
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMd5.wdl
    
  - name: VUMCCopyFile
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCopyFile.wdl
 
  - name: VUMCCramQC2
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC2.wdl

  - name: VUMCCramQCCombined
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC_combined.wdl

  - name: VUMCSamHeader
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCSamHeader.wdl

  - name: VUMCDeleteFiles
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteFiles.wdl

  - name: VUMCBamToCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCBamToCram.wdl

  - name: VUMCFastqToAlignedCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedCram.wdl

  - name: VUMCMoveCram
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCMoveCram.wdl

  - name: VUMCDeleteBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCDeleteBam.wdl
