version: 1.2
workflows:
  - name: VUMCFastqToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedBam.wdl

  - name: VUMCUnmappedBamToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCUnmappedBamToAlignedBam.wdl

  - name: VUMCFastqQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqQC.wdl

  - name: VUMCCramQC
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCCramQC.wdl
