version: 1.2
workflows:

  - name: Optimus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/optimus/Optimus.wdl

  - name: Smartseq2_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_multisample/MultiSampleSmartSeq2.wdl

  - name: Smartseq2_Single_Sample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_sample/SmartSeq2SingleSample.wdl

  - name: Smartseq2_Single_Nucleus_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus_multisample/MultiSampleSmartSeq2SingleNucleus.wdl

  - name: Smartseq2_Single_Nucleus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_nucleus/SmartSeq2SingleNucleus.wdl

  - name: IlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/genotyping/illumina/IlluminaGenotypingArray.wdl

  - name: scATAC
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/scATAC/scATAC.wdl

  - name: JointGenotyping
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/JointGenotyping.wdl

  - name: ExomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/exome/ExomeGermlineSingleSample.wdl

  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

  - name: OptimusHcaAdapter
    subclass: WDL
    primaryDescriptorPath: /projects/optimus/CreateOptimusAdapterMetadata.wdl
    
  - name: Ss2HcaAdapter
    subclass: WDL
    primaryDescriptorPath: /projects/smartseq2/CreateSs2AdapterMetadata.wdl

  - name: CEMBA
    subclass: WDL
    primaryDescriptorPath: /pipelines/cemba/cemba_methylcseq/CEMBA.wdl

  - name: ReblockGVCF
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/joint_genotyping/reblocking/ReblockGVCF.wdl

  - name: Arrays
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/single_sample/Arrays.wdl

  - name: Imputation
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation/Imputation.wdl

