version: 1.2
workflows:
  - name: Optimus
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/optimus/Optimus.wdl
  - name: Smartseq2_Multisample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_multisample/MultiSampleSmartSeq2.wdl
  - name: Smartseq2_Single_Sample
    subclass: WDL
    primaryDescriptorPath: /pipelines/skylab/smartseq2_single_sample/SmartSeq2SingleSample.wdl
  - name: IlluminaGenotypingArray
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/genotyping/illumina/IlluminaGenotypingArray.wdl
