version: 1.2
workflows:
  - name: VUMCFastqToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCFastqToAlignedBam.wdl

  - name: VUMCUnmappedBamToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /pipelines/vumc_biostatistics/preprocessing/VUMCUnmappedBamToAlignedBam.wdl
      testParameterFiles:
        - /pipelines/vumc_biostatistics/preprocessing/VUMCUnmappedBamToAlignedBam.inputs.terra.json