/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class BillingAccount(
    /* name of billing account */
    accountName: String,
    /* whether the FireCloud service has been given access to this billing account */
    firecloudHasAccess: Boolean,
    /* display name of billing account */
    displayName: String
)
