/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class BillingProjectMembership(
    /* the name of the project to create */
    projectName: String,
    /* the role of the current user in the project */
    role: String,
    status: String,
    /* informational message about the project */
    message: Option[String] = None
)
