/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class ConfigurationPayloadMethodRepoMethod(
    /* Name of referenced method */
    methodName: Option[String] = None,
    /* Namespace of referenced method */
    methodNamespace: Option[String] = None,
    /* Snapshot ID of referenced method */
    methodVersion: Option[Integer] = None
)
