/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class ConfigurationIngest(
    /* Method configuration namespace */
    namespace: String,
    /* Method configuration name */
    name: String,
    /* Root entity type */
    rootEntityType: String,
    /* Map[String, String] with corresponding workspace-related information - name and namespace */
    workspaceName: Any,
    /* Map[String, String] with corresponding method-related information */
    methodRepoMethod: Any,
    /* Map[String, String] with outputs information */
    outputs: Any,
    /* Map[String, String] with inputs information */
    inputs: Any,
    /* Map[String, String] of prerequisites (keys unused, will be removed in the future) */
    prerequisites: Any
)
