/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class Consent(
    /* The ID of the entity. */
    consentId: Option[String] = None,
    /* Name used to identify the consent. */
    name: Option[String] = None,
    /* Creation Date in date-time milliseconds */
    createDate: Option[Number] = None,
    /* Date of the last update in date-time milliseconds */
    lastUpdate: Option[Number] = None,
    /* The lastest modification date in date-time milliseconds */
    sortDate: Option[Number] = None,
    /* Describes if this consent has to be reviewed manually. */
    requiresManualReview: Option[Boolean] = None,
    /* The URL of the saved file. */
    dataUseLetter: Option[String] = None,
    /* The UseRestriction of this consent. Used to match against another entities. */
    useRestriction: Option[Any] = None,
    /* Name that identifies the Data Use Letter file. */
    dulName: Option[String] = None,
    /* The translated use restriction of the consent. */
    translatedUseRestriction: Option[String] = None
)
