/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class CopyEntity(
    /* Source Workspace Namespace */
    sourceWorkspace: Option[Namespace] = None,
    /* Entity Type */
    entityType: Option[String] = None,
    /* List of entity names to be copied */
    entityNames: Option[List[String]] = None
)
