/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class DatasetPermission(
    /* the name of the NIH dataset */
    name: Option[String] = None,
    /* true if you have access to the dataset, false otherwise */
    authorized: Option[Boolean] = None
)
