/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class EntityCopyResponse(
    /* the entities that were successfully copied into the workspace */
    entitiesCopied: List[AttributeEntityReference],
    /* these entities already exist in your workspace */
    hardConflicts: List[EntityHardConflict],
    /* the conflicts within your entity subtrees. note that this will be empty if there are hard conflicts */
    softConflicts: List[EntitySoftConflict]
)
