/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class EntityQueryParameters(
    /* page number, 1-indexed positive integer */
    page: Number,
    /* count of items per page, positive integer */
    pageSize: Number,
    /* field to sort by */
    sortField: String,
    /* asc or desc */
    sortDirection: String,
    /* terms to filter results by */
    filterTerms: Option[String] = None
)
