/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class EntityAccessControl(
    /* method repo method */
    method: Option[MethodShort] = None,
    /* workspace configuration that references the method */
    referencedBy: MethodConfigurationName,
    /* method repo ACLs for the referenced method */
    acls: List[FireCloudPermission],
    /* error message generated when retrieving acls for this method */
    message: Option[String] = None
)
