/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

import org.broadinstitute.dsp.pipelines.firecloud.model.FireCloudEntity

case class Entity(
    /* The name of the entity */
    name: String,
    /* The type of the entity */
    entityType: String,
    /* Map[String,Attribute] */
    attributes: Map[String, String]
) extends FireCloudEntity
