/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

import java.util.Date

case class ExecutionEvent(
    /* Description of the event */
    description: String,
    /* When the event started */
    startTime: Date,
    /* When the event finished */
    endTime: Option[Date] = None
)
