/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class ExtendedEnabled(
    /* User enabled via Google? */
    google: Option[Boolean] = None,
    /* User enabled in LDAP? */
    ldap: Option[Boolean] = None,
    /* User is a member of the \"All Users\" group? */
    allUsersGroup: Option[Boolean] = None
)
