/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class Metadata(
    /* The version of this registry */
    version: String,
    /* The version of the GA4GH tool-registry API supported by this registry */
    apiVersion: String,
    /* A country code for the registry (ISO 3166-1 alpha-3) */
    country: Option[String] = None,
    /* A friendly name that can be used in addition to the hostname to describe a registry */
    friendlyName: Option[String] = None
)
