/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class MethodConfiguration(
    /* This method configuration's namespace */
    namespace: String,
    /* The name of the method configuration */
    name: String,
    /* The root entity type that the method will be running on */
    rootEntityType: String,
    /* Map[String, String] */
    prerequisites: Option[Any] = None,
    /* Map[String, String] */
    inputs: Any,
    /* Map[String, String] */
    outputs: Option[Any] = None,
    /* The properties of the method from the method store that this config is associated with */
    methodRepoMethod: MethodRepoMethod
)
