/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class MethodAclPair(
    method: MethodRepoMethod,
    acls: List[FireCloudPermission],
    /* ignored during input; if present during output, contains error messages */
    message: Option[String] = None
)
