/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class PermissionReportRequest(
    /* list of email addresses; optional; defaults to all users in the workspace */
    users: Option[List[String]] = None,
    /* list of configs; optional; defaults to all configs in the workspace */
    configs: Option[List[MethodConfigurationName]] = None
)
