/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class Profile(
    /* User's first name */
    firstName: String,
    /* User's last name */
    lastName: String,
    /* User's title */
    title: String,
    /* User's contact email (if different from account email) */
    contactEmail: Option[String] = None,
    /* User's home institution */
    institute: String,
    /* User's institutional program */
    institutionalProgram: String,
    /* User's program location city */
    programLocationCity: String,
    /* User's program location state */
    programLocationState: String,
    /* User's program location country */
    programLocationCountry: String,
    /* Principal Investigator */
    pi: String,
    /* User's program non-profit status */
    nonProfitStatus: String
)
