/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class SubmissionRequest(
    /* Namespace of the method configuration to execute. */
    methodConfigurationNamespace: String,
    /* Name of the method configuration to execute. */
    methodConfigurationName: String,
    /* Type of root entity for expression. */
    entityType: String,
    /* Name of root entity for expression. */
    entityName: String,
    /* Expression that resolves to one or more entities matching the entity type in the method configuration. */
    expression: Option[String] = None,
    /* Whether or not to read from cache for this submission. */
    useCallCache: Boolean,
    /* What happens after a task fails. Choose from ContinueWhilePossible and NoNewCalls. Defaults to NoNewCalls if not specified. See Cromwell docs for more information. */
    workflowFailureMode: Option[String] = None
)
