/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class SubmissionValidationValue(
    /* the value of the input expression for the specified entity */
    value: Option[String] = None,
    /* parsing error(s) */
    error: Option[String] = None,
    /* name of input */
    inputName: String
)
