/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class ToolClass(
    /* The unique identifier for the class */
    id: Option[String] = None,
    /* A short friendly name for the class */
    name: Option[String] = None,
    /* A longer explanation of what this class is and what it can accomplish */
    description: Option[String] = None
)
