/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class ToolVersion(
    /* The name of the version. */
    name: Option[String] = None,
    /* The URL for this tool in this registry, for example `http://agora.broadinstitute.org/tools/123456/1` */
    url: String,
    /* An identifier of the version of this tool for this particular tool registry, for example `v1` */
    id: String,
    /* The docker path to the image (and version) for this tool. (e.g. quay.io/seqware/seqware_full/1.1). This always returns an empty string. */
    image: Option[String] = None,
    /* The type (or types) of descriptors available. */
    descriptorType: Option[List[String]] = None,
    /* Reports if this tool has a dockerfile available. This always returns false. */
    dockerfile: Option[Boolean] = None,
    /* The version of this tool version in the registry. Iterates when fields like the description, author, etc. are updated. */
    metaVersion: String
)
