/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class WorkspaceIngest(
    /* New workspace namespace */
    namespace: String,
    /* New workspace name */
    name: String,
    /* Map of attributes */
    attributes: Map[String, String],
    /* The list of groups to form the Authorization Domain (empty if no Authorization Domain is set) */
    authorizationDomain: Option[List[ManagedGroupRef]] = None
)
