/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class WorkspaceAccessEntry(
    /* The access level granted to this user or group (OWNER, READER, WRITER, NO ACCESS) */
    accessLevel: String,
    /* The status of the users access */
    pending: Boolean,
    /* True if the user can share the workspace with others, false otherwise */
    canShare: Boolean,
    /* True if the user can launch compute in this workspace, false otherwise */
    canCompute: Boolean
)
