/**
  * FireCloud
  * Genome analysis execution service.
  *
  * OpenAPI spec version: 0.1
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package org.broadinstitute.dsp.pipelines.firecloud.model.autogen

case class WorkspaceACLUpdateResponseList(
    /* the users or groups who were updated */
    usersUpdated: List[WorkspaceACLUpdateResponse],
    /* the list of invites that were sent */
    invitesSent: List[WorkspaceACLUpdate],
    /* the list of invites that were updated */
    invitesUpdated: List[WorkspaceACLUpdate],
    /* the users or groups who were not found */
    usersNotFound: List[WorkspaceACLUpdate]
)
