version 1.0

# This workflow trains and tests a model with the HGDP information.
# The end of the stdout of train_and_test_model contains confusion matrices
workflow select_samples_for_training {
    input {
        # The HGDP sample metadata file
        File? hgdp_metadata_file_in

        # These are generated by determine_hq_sites.wdl.  I.e. the high-quality sites w/ and w/o the sample data
        File vcf_bgz_merged_sites_only
        File vcf_bgz_merged_sites_only_index
        File vcf_bgz_merged_full
        File vcf_bgz_merged_full_index

        # Minimum number of hodout samples for testing.
        Int? min_holdout_in
        Float other_cutoff=0.7

    }
    File hgdp_metadata_file = select_first([hgdp_metadata_file_in, "gs://gcp-public-data--gnomad/release/3.1/secondary_analyses/hgdp_1kg_v2/metadata_and_qc/gnomad_meta_updated.tsv"])

    call select_sample_sets {
        input:
            hgdp_metadata_file = hgdp_metadata_file,
            is_train_for_oth_in = false,
            min_holdout_in = min_holdout_in
    }

    call create_bgz_with_select_samples as create_bgz_with_select_samples_training {
        input:
            full_bgz = vcf_bgz_merged_full,
            full_bgz_index = vcf_bgz_merged_full_index,
            high_quality_sites_vcf = vcf_bgz_merged_sites_only,
            high_quality_sites_vcf_index = vcf_bgz_merged_sites_only_index,
            sample_lists_to_include = select_sample_sets.training_sample_lists,
            output_basename = "training_set_"
    }

    call create_bgz_with_select_samples as create_bgz_with_select_samples_testing {
        input:
            full_bgz =  vcf_bgz_merged_full,
            full_bgz_index = vcf_bgz_merged_full_index,
            high_quality_sites_vcf = vcf_bgz_merged_sites_only,
            high_quality_sites_vcf_index = vcf_bgz_merged_sites_only_index,
            sample_lists_to_include = select_sample_sets.testing_sample_lists,
            output_basename = "testing_set_"
    }

    call create_hw_pca_training {
        input:
            full_bgz = create_bgz_with_select_samples_training.out_bgz,
            full_bgz_index = create_bgz_with_select_samples_training.out_bgz_idx,
            hgdp_metadata_file = hgdp_metadata_file
    }

    call train_and_test_model as train_and_test_model_oth {
        input:
            training_pca_labels_ht_tar_gz = create_hw_pca_training.training_pca_labels_ht_tar_gz,
            loadings_training_ht_tar_gz = create_hw_pca_training.loadings_training_ht_tar_gz,
            pop_label_ht_tar_gz = create_hw_pca_training.pop_label_ht_tar_gz,
            training_full_bgz = create_bgz_with_select_samples_training.out_bgz,
            training_full_bgz_index = create_bgz_with_select_samples_training.out_bgz_idx,
            testing_full_bgz = create_bgz_with_select_samples_testing.out_bgz,
            testing_full_bgz_index = create_bgz_with_select_samples_testing.out_bgz_idx,
            hgdp_metadata_file = hgdp_metadata_file,
            is_testing_oth_in = true,
            other_cutoff = other_cutoff,
    }

    call train_and_test_model as train_and_test_model_no_oth {
        input:
            training_pca_labels_ht_tar_gz = create_hw_pca_training.training_pca_labels_ht_tar_gz,
            loadings_training_ht_tar_gz = create_hw_pca_training.loadings_training_ht_tar_gz,
            pop_label_ht_tar_gz = create_hw_pca_training.pop_label_ht_tar_gz,
            training_full_bgz = create_bgz_with_select_samples_training.out_bgz,
            training_full_bgz_index = create_bgz_with_select_samples_training.out_bgz_idx,
            testing_full_bgz = create_bgz_with_select_samples_testing.out_bgz,
            testing_full_bgz_index = create_bgz_with_select_samples_testing.out_bgz_idx,
            hgdp_metadata_file = hgdp_metadata_file,
            is_testing_oth_in = false,
            other_cutoff = other_cutoff
    }

    output {
        File stdout_holdout_test_results =  train_and_test_model_oth.results
        File stdout_holdout_test_results_no_oth =  train_and_test_model_no_oth.results
        File tsv_holdout_test_results =  train_and_test_model_oth.results_df
        File tsv_holdout_test_results_no_oth =  train_and_test_model_no_oth.results_df
        File pop_label_ht_tar_gz = create_hw_pca_training.pop_label_ht_tar_gz
        File training_vcf_bgz = create_bgz_with_select_samples_training.out_bgz
        File training_vcf_bgz_idx = create_bgz_with_select_samples_training.out_bgz_idx
    }
}

task select_sample_sets {
    input {
        File hgdp_metadata_file
        Boolean is_train_for_oth_in
        Int? min_holdout_in
    }
    String is_not_train_for_oth = if (is_train_for_oth_in) then 'False' else 'True'
    Int min_holdout = if (defined(min_holdout_in)) then min_holdout_in else 10
    command <<<

        python3 <<EOF

        # Write the sample files
        import numpy as np
        import math
        np.random.seed(337337)
        import pandas as pd

        # Read in metadata for ALL samples
        metadata_pd = pd.read_csv("~{hgdp_metadata_file}", sep="\t")

        num_training_samples_per_pop = 350
        num_testing_samples_per_pop = 200

        num_holdout = ~{min_holdout}

        # 'project_meta.project_popp' is the column we treat as ancestry label
        #   We collapse FIN and NFE as eur.
        pops = {
        'afr':metadata_pd['project_meta.project_pop'] == 'afr',
        'eas':metadata_pd['project_meta.project_pop'] == 'eas',
        'sas':metadata_pd['project_meta.project_pop'] == 'sas',
        'eur':(metadata_pd['project_meta.project_pop'] == 'nfe') | (metadata_pd['project_meta.project_pop'] == 'fin') ,
        'amr':metadata_pd['project_meta.project_pop'] == 'amr',
        'mid':metadata_pd['project_meta.project_pop'] == 'mid',
        'oth':metadata_pd['project_meta.project_pop'] == 'oth'
        }

        for p in pops.keys():
            metadata_pop = metadata_pd[ pops[p] ]

            # We do not want to include "oth" in our training.  We will want it as labeled test data though.
            #  If we decide to train on "oth" in the future, remove the if statement:
            #
            if p == 'oth' and ~{is_not_train_for_oth}:
                num_to_training = 0
                num_to_testing = len(metadata_pop)
            else:

                # Samples the training AND test sets in one go.  Then grab the first X as training and the second Y as test.
                num_to_sample = min(num_training_samples_per_pop + num_testing_samples_per_pop, len(metadata_pop))

                # Maintain that we always have at least 10 samples to test.
                if num_to_sample == len(metadata_pop):
                    num_to_training = len(metadata_pop) - num_holdout
                    num_to_testing = num_holdout
                else:
                    num_to_training = num_training_samples_per_pop
                    num_to_testing = num_testing_samples_per_pop

            metadata_pop_sampled = metadata_pop.sample(n=num_to_training+num_to_testing)

            metadata_training = metadata_pop_sampled[0:num_to_training]
            training_sample_names = metadata_training['s'].tolist()

            metadata_testing = metadata_pop_sampled[num_to_training:(num_to_training+num_to_testing)]
            testing_sample_names = metadata_testing['s'].tolist()

            fp = open("training_samples_" + p + ".args", 'w')
            fp.write("\n".join(training_sample_names))
            fp.flush()
            fp.close()

            fp = open("testing_samples_" + p + ".args", 'w')
            fp.write("\n".join(testing_sample_names))
            fp.flush()
            fp.close()

        print(metadata_pd['project_meta.project_pop'].value_counts())

        EOF
    >>>

    output {
        Array[File] training_sample_lists = glob("training_samples*.args")
        Array[File] testing_sample_lists = glob("testing_samples*.args")
    }

    runtime {
        docker: "us.gcr.io/broad-gatk/gatk:4.2.0.0"
        memory: "3 GB"
        cpu: "1"
        disks: "local-disk 100 HDD"
    }
}

task create_bgz_with_select_samples {
    input {
        File full_bgz
        File full_bgz_index
        File high_quality_sites_vcf
        File high_quality_sites_vcf_index

        # Each of these files has a list of sample IDs
        Array[File] sample_lists_to_include

        # A simple string without any parh information/characters
        String output_basename
    }

    String output_filename = output_basename + ".vcf.bgz"
    String output_filename_idx = output_basename + ".vcf.bgz.tbi"

    command <<<
        gatk  SelectVariants \
        -V "~{full_bgz}" \
        -L "~{high_quality_sites_vcf}" \
        -sn ~{sep=' -sn ' sample_lists_to_include} \
        -O "~{output_filename}"

        gatk IndexFeatureFile -I ~{output_filename} -O ~{output_filename_idx}

    >>>

    output {
        File out_bgz = "~{output_filename}"
        File out_bgz_idx = "~{output_filename_idx}"
    }

    runtime {
        docker: "us.gcr.io/broad-gatk/gatk:4.2.0.0"
        memory: "7 GB"
        cpu: "1"
        disks: "local-disk 300 HDD"
    }
}

task create_hw_pca_training {
    input {
        File full_bgz
        File full_bgz_index
        File hgdp_metadata_file
    }
    parameter_meta {
        full_bgz: {localization_optional: true}
        full_bgz_index: {localization_optional: true}
    }
    command <<<
        set -e
        python3 <<EOF

        import pandas as pd
        import numpy as np
        import hail as hl
        hl.init(default_reference='GRCh38', idempotent=True)

        import pandas as pd

        # Read in metadata for ALL samples
        metadata_pd = pd.read_csv("~{hgdp_metadata_file}", sep="\t")

        def get_PCA_scores(vcf_bgz:str):
            v = hl.import_vcf(vcf_bgz, force_bgz=True)
            eigenvalues, scores, loadings = hl.hwe_normalized_pca(v.GT, k=16, compute_loadings=True)
            return eigenvalues, scores, loadings

        def collapse_fin_to_eur(pop):
            if pop=='fin' or pop=='nfe':
                return 'eur'
            else:
                return pop

        _, scores_training, loadings_training = get_PCA_scores("~{full_bgz}")

        # Apply any custom processing to the population labels from the training data
        pop_label_pd = metadata_pd[['s', 'project_meta.project_pop']]
        pop_label_pd['pop_label'] = metadata_pd['project_meta.project_pop'].apply(collapse_fin_to_eur)

        # Join the labels to the training PCA feature set.
        pop_label_ht = hl.Table.from_pandas(pop_label_pd).key_by('s')
        pop_label_ht.describe()
        training_pca_ht = scores_training.join(pop_label_ht, how='inner')

        # Write out the training pca and loadings information
        training_pca_ht.write('training_pca.ht')
        loadings_training.write('loadings_training.ht')
        pop_label_ht.write('pop_label.ht')

        EOF

        # tar the Hail Tables for output in cromwell
        tar zcvf training_pca.ht.tar.gz training_pca.ht
        tar zcvf loadings_training.ht.tar.gz loadings_training.ht
        tar zcvf pop_label.ht.tar.gz pop_label.ht
    >>>

    output {
        File training_pca_labels_ht_tar_gz = "training_pca.ht.tar.gz"
        File loadings_training_ht_tar_gz = "loadings_training.ht.tar.gz"
        File pop_label_ht_tar_gz = "pop_label.ht.tar.gz"
    }

    runtime {
        docker: "hailgenetics/hail:0.2.67"
        memory: "123 GB"
        cpu: "4"
        disks: "local-disk 500 HDD"
    }
}

# TODO: Reduce code dupes w/ run_ancestry
task train_and_test_model {
    input {
        File training_pca_labels_ht_tar_gz
        File loadings_training_ht_tar_gz
        File pop_label_ht_tar_gz
        File training_full_bgz
        File training_full_bgz_index
        File testing_full_bgz
        File testing_full_bgz_index
        File hgdp_metadata_file
        Boolean is_testing_oth_in
        # Should be between 0 and 1.0.  If you are unsure, just use 0.75.  This is ignored if is_testing_oth_in is false
        Float other_cutoff
    }

    String is_testing_oth = if (is_testing_oth_in) then 'True' else 'False'

    parameter_meta {
        training_full_bgz: {localization_optional: true}
        training_full_bgz_index: {localization_optional: true}
        testing_full_bgz: {localization_optional: true}
        testing_full_bgz_index: {localization_optional: true}
     }

    command <<<
        set -e

        tar zxvf ~{training_pca_labels_ht_tar_gz}
        tar zxvf ~{loadings_training_ht_tar_gz}
        tar zxvf ~{pop_label_ht_tar_gz}
        ls -la

        python3 <<EOF

        import pandas as pd
        import numpy as np
        import hail as hl
        hl.init(default_reference='GRCh38', idempotent=True)
        import pandas as pd
        from sklearn.ensemble import RandomForestClassifier
        import numpy as np

        def predict_other(r, c=~{other_cutoff}):
            pred = r.preds
            probs = r.probabilities
            probs = [float(x) for x in probs]
            if max(probs) > c:
                return pred
            else:
                return "oth"

        def collapse_for_aou(pop:str):
            if pop == "eas" or pop == "sas":
                return "as"
            if pop == "nfe" or pop == "fin":
                return 'eur'
            else:
                return pop

        # Load up the training information.  The training PCA also has the label information
        training_pca_ht = hl.methods.read_table('training_pca.ht')
        loadings_training = hl.methods.read_table('loadings_training.ht')
        pop_label_ht =  hl.methods.read_table('pop_label.ht')

        # Prepare testing data
        testing_mt = hl.import_vcf("~{testing_full_bgz}", force_bgz=True)
        testing_mt = testing_mt.annotate_cols(population = pop_label_ht[testing_mt.s]['pop_label'])

        # Prepare loadings
        training_mt = hl.import_vcf("~{training_full_bgz}", force_bgz=True)
        training_mt = training_mt.annotate_rows(af2=hl.agg.mean(training_mt.GT.n_alt_alleles()) / 2)
        loadings_training = loadings_training.annotate(af=training_mt.rows()[loadings_training.key].af2)

        reduced_training_pca_ht = training_pca_ht.filter((training_pca_ht['pop_label'] != "oth"))

        # Train a random forest
        clf = RandomForestClassifier(random_state=337337)
        X = reduced_training_pca_ht.scores.collect()
        y = reduced_training_pca_ht['pop_label'].collect()
        print("Using " + str(len(y)) + " sample labels for training.")
        print("Using " + str(len(X)) + " samples for training.")
        clf.fit(X, y)

        # Project the test set into PCA space
        testing_ht = hl.experimental.pc_project(testing_mt.GT, loadings_training.loadings, loadings_training.af)
        testing_ht = testing_ht.annotate(population=testing_mt.cols()[testing_ht.s].population)

        print("testing_ht: " + str(len(testing_ht.population.collect())) )

        if ~{is_testing_oth}:
            reduced_testing_ht = testing_ht
        else:
            # Test the random forest on a holdout set, without testing other just yet
            reduced_testing_ht = testing_ht.filter((testing_ht['population'] != "oth"))

        test_X = reduced_testing_ht.scores.collect()
        print(len(test_X))
        test_y = reduced_testing_ht.population.collect()
        preds = clf.predict(test_X)
        probs = clf.predict_proba(test_X)
        probs_list = probs.tolist()

        results_df = pd.DataFrame({'s': reduced_testing_ht.s.collect(), "preds": preds, "test_y":test_y, "probabilities":probs_list})
        results_df['is_correct'] = results_df['preds'] == results_df['test_y']

        results_df['preds_oth'] = results_df[['preds', 'probabilities']].apply(predict_other, axis = 1)
        results_df['test_y_aou'] = results_df['test_y'].apply(collapse_for_aou)
        results_df['preds_aou'] = results_df['preds'].apply(collapse_for_aou)
        results_df['is_correct_aou'] = results_df['preds_aou'] == results_df['test_y_aou']

        error_rate = 1.0 - (float(np.sum(results_df["is_correct"] == True))/float(len(results_df)))
        print(f'Error rate not including "oth": {error_rate}')

        confusion_matrix = pd.crosstab(results_df['test_y'], results_df['preds'], rownames=['Actual'], colnames=['Predicted'])
        print (confusion_matrix)

        error_rate_aou = 1.0 - (float(np.sum(results_df["is_correct_aou"] == True))/float(len(results_df)))
        print(f'Error rate (accounting for AoU surveys), not incl. oth: {error_rate_aou}')

        confusion_matrix = pd.crosstab(results_df['test_y_aou'], results_df['preds_aou'], rownames=['Actual'], colnames=['Predicted'])
        print (confusion_matrix)

        if ~{is_testing_oth}:
            print("OTHER CUTOFF: " + str(~{other_cutoff}))
            results_df['is_correct_oth'] = results_df['preds_oth'] == results_df['test_y']
            error_rate = 1.0 - (float(np.sum(results_df["is_correct_oth"] == True))/float(len(results_df)))
            print(f'Error rate w/ oth, but without AoU collapsed ancestries: {error_rate}')

            confusion_matrix = pd.crosstab(results_df['test_y'], results_df['preds_oth'], rownames=['Actual'], colnames=['Predicted'])
            print(confusion_matrix)

            print("Testing other cutoffs:")
            cutoffs_to_test = np.linspace(0.65,0.97, 17).tolist()

            for i,c in enumerate(cutoffs_to_test):
                c_str = str(c)
                results_df['preds_oth_'+c_str] = results_df[['preds', 'probabilities']].apply(predict_other, c=c, axis = 1)
                results_df['is_correct_oth_'+c_str] = results_df['preds_oth_'+c_str] == results_df['test_y']

                print(f'Cutoff: {c_str}')
                confusion_matrix = pd.crosstab(results_df['test_y'], results_df['preds_oth_'+c_str], rownames=['Actual'], colnames=['Predicted'])
                error_rate = 1.0 - (float(np.sum(results_df["is_correct_oth_"+c_str] == True))/float(len(results_df)))
                print(f'Error rate w/ oth and cutoff {c_str}: {error_rate}')
                print(confusion_matrix)
        results_df.to_csv("results_df_~{is_testing_oth}.tsv", sep="\t")
        EOF
    >>>

    output {
        File results = stdout()
        File results_df = "results_df_~{is_testing_oth}.tsv"
    }

    runtime{
        docker: "hailgenetics/hail:0.2.67"
        memory: "123 GB"
        cpu: "4"
        disks: "local-disk 500 HDD"
    }
}