name: Authorized Users

on:
  workflow_call:
    outputs:
      approved:
        description: 'Whether the user is approved'
        value: ${{ jobs.check-authorization.outputs.approved }}

jobs:
  check-authorization:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.gatekeeper.outputs.approved }}
    steps:
      - name: Check if user is approved
        id: gatekeeper
        run: |
          # Define the allowlist of users and teams
          echo "The actor is: ${GITHUB_ACTOR}"
          APPROVED_USERS=("nikellepetrillo")

          # Check if the user is in the allowlist
          if [[ " ${APPROVED_USERS[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
            echo "User ${GITHUB_ACTOR} is approved."
            echo "approved=false" >> $GITHUB_OUTPUT
          else
            echo "User ${GITHUB_ACTOR} is not approved."
            echo "approved=false" >> $GITHUB_OUTPUT
          fi