name: Test ExomeGermlineSingleSample

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "develop", "staging", "master" ]
    # Only run if files in these paths changed:
    ####################################
    # SET PIPELINE SPECIFIC PATHS HERE #
    ####################################
    paths:
      # anything in the pipelines folder
      - 'pipelines/wdl/dna_seq/germline/single_sample/exome/**'
      # tasks from the pipeline WDL and their dependencies
      - 'tasks/wdl/UnmappedBamToAlignedBam.wdl'
      - 'tasks/wdl/AggregatedBamQC.wdl'
      - 'tasks/wdl/Qc.wdl'
      - 'tasks/wdl/BamProcessing.wdl'
      - 'tasks/wdl/BamToCram.wdl'
      - 'structs/dna_seq/DNASeqStructs.wdl'
      - 'pipelines/wdl/dna_seq/germline/variant_calling/VariantCalling.wdl'
      - 'tasks/wdl/GermlineVariantDiscovery.wdl'
      - 'tasks/wdl/Utilities.wdl'
      - 'tasks/wdl/DragenTasks.wdl'
      - 'tasks/wdl/Qc.wdl'
      - 'tasks/wdl/Utilities.wdl'
      # verification WDL and its dependencies
      - 'verification/VerifyGermlineSingleSample.wdl'
      - 'verification/VerifyMetrics.wdl'
      - 'verification/VerifyTasks.wdl'
      # test WDL and its dependencies
      - 'verification/test-wdls/TestExomeGermlineSingleSample.wdl'
      - 'tasks/wdl/TerraCopyFilesFromCloudToCloud.wdl'
      # this file, the subworkflow file, and the firecloud_api script
      - '.github/workflows/test_exome_germline_single_sample.yml'
      - '.github/workflows/warp_test_workflow.yml'
      - 'scripts/firecloud_api/firecloud_api.py'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      useCallCache:
        description: 'Use call cache (default: true)'
        required: false
        default: "true"
      updateTruth:
        description: 'Update truth files (default: false)'
        required: false
        default: "false"
      testType:
        description: 'Specify the type of test (Plumbing or Scientific)'
        required: false
        type: choice
        options:
          - Plumbing
          - Scientific
      truthBranch:
        description: 'Specify the branch for truth files (default: master)'
        required: false
        default: "master"

jobs:
  TestExomeGermlineSingleSample:
    uses: ./.github/workflows/warp_test_workflow.yml
    with:
      pipeline_name: TestExomeGermlineSingleSample
      dockstore_pipeline_name: ExomeGermlineSingleSample
      pipeline_dir: pipelines/wdl/dna_seq/germline/single_sample/exome
      use_call_cache: ${{ github.event.inputs.useCallCache || 'true' }}
      update_truth: ${{ github.event.inputs.updateTruth || 'false' }}
      test_type: ${{ github.event.inputs.testType }}
      truth_branch: ${{ github.event.inputs.truthBranch || 'master' }}
    secrets:
      PDT_TESTER_SA_B64: ${{ secrets.PDT_TESTER_SA_B64 }}
      DOCKSTORE_TOKEN: ${{ secrets.DOCKSTORE_TOKEN }}