name: Test WholeGenomeReprocessing

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "develop", "staging", "master" ]
    # Only run if files in these paths changed:
    ####################################
    # SET PIPELINE SPECIFIC PATHS HERE #
    ####################################
    paths:
      # anything in the pipelines folder
      - 'pipelines/wdl/reprocessing/wgs/**'
      - 'pipelines/wdl/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl'
      # tasks from the pipeline WDL and their dependencies
      - 'structs/dna_seq/DNASeqStructs.wdl'
      - 'tasks/wdl/Alignment.wdl'
      - 'tasks/wdl/DragmapAlignment.wdl'
      - 'tasks/wdl/SplitLargeReadGroup.wdl'
      - 'tasks/wdl/BamProcessing.wdl'
      - 'tasks/wdl/Utilities.wdl'
      - 'tasks/wdl/Qc.wdl'
      - 'tasks/wdl/AggregatedBamQC.wdl'
      - 'tasks/wdl/BamToCram.wdl'
      - 'pipelines/wdl/dna_seq/germline/variant_calling/VariantCalling.wdl'
      - 'pipelines/wdl/reprocessing/cram_to_unmapped_bams/CramToUnmappedBams.wdl'
      - 'tasks/wdl/GermlineVariantDiscovery.wdl'
      - 'tasks/wdl/DragenTasks.wdl'
      # verification WDL and its dependencies
      - 'verification/VerifyExomeReprocessing.wdl'
      - 'verification/VerifyGermlineSingleSample.wdl'
      - 'verification/VerifyMetrics.wdl'
      - 'verification/VerifyTasks.wdl'
      # test WDL and its dependencies
      - 'verification/test-wdls/TestWholeGenomeGermlineSingleSample.wdl'
      - 'tasks/wdl/TerraCopyFilesFromCloudToCloud.wdl'
      # this file, the subworkflow file, and the firecloud_api script
      - '.github/workflows/test_whole_genome_reprocessing.yml'
      - '.github/workflows/warp_test_workflow.yml'
      - 'scripts/firecloud_api/firecloud_api.py'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      useCallCache:
        description: 'Use call cache (default: true)'
        required: false
        default: "true"
      updateTruth:
        description: 'Update truth files (default: false)'
        required: false
        default: "false"
      testType:
        description: 'Specify the type of test (Plumbing or Scientific)'
        required: false
        type: choice
        options:
          - Plumbing
          - Scientific
      truthBranch:
        description: 'Specify the branch for truth files (default: master)'
        required: false
        default: "master"

jobs:
  TestWholeGenomeReprocessing:
    uses: ./.github/workflows/warp_test_workflow.yml
    with:
      pipeline_name: TestWholeGenomeReprocessing
      dockstore_pipeline_name: WholeGenomeReprocessing
      pipeline_dir: pipelines/wdl/reprocessing/wgs
      use_call_cache: ${{ github.event.inputs.useCallCache || 'true' }}
      update_truth: ${{ github.event.inputs.updateTruth || 'false' }}
      test_type: ${{ github.event.inputs.testType }}
      truth_branch: ${{ github.event.inputs.truthBranch || 'master' }}
    secrets:
      PDT_TESTER_SA_B64: ${{ secrets.PDT_TESTER_SA_B64 }}
      DOCKSTORE_TOKEN: ${{ secrets.DOCKSTORE_TOKEN }}