
# This workflow validates all pipeline WDL files (those found in the pipelines/ projects/ and beta-pipelines directories) using the 'miniwdl' tool.
name: MiniWdlCheck

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  validate_wdl_job:
    runs-on: ubuntu-latest
    name: Validate all wdl using miniwdl
    steps:
      - uses: actions/checkout@v2
        with:
          repository: broadinstitute/warp
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install mini-wdl
        run: |
          python -m pip install --upgrade pip
          pip3 install miniwdl
      - name: Run miniwdl
        run: |
          ./scripts/miniwdl_check.sh